config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: "dashboards#index"

  resources :pizzas do
    resources :toppings, only: [:create, :destroy, :update]
  end
  
  resources :toppings
end

app/models/topping.rb
class Topping < ApplicationRecord
  has_many :pizza_toppings, dependent: :destroy
  has_many :pizzas, through: :pizza_toppings

  validates :name, presence: true, uniqueness: true
  validates :quantity, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
end

app/controllers/toppings_controller.rb
class ToppingsController < ApplicationController
  include Pundit::Authorization
  before_action :set_topping, only: %i[edit update destroy]

  def index
    authorize Topping
    @toppings = policy_scope(Topping).order(:created_at)
    @topping = Topping.new
  end

  def create
    @topping = Topping.new(topping_params)
    authorize @topping
    if @topping.save
      respond_to do |format|
        format.turbo_stream do
          render turbo_stream: [
            turbo_stream.replace('toppings_form', partial: 'form', locals: { topping: Topping.new }),
            turbo_stream.append('toppings_list', partial: 'topping', locals: { topping: @topping })
          ]
        end
        format.html { redirect_to toppings_path, notice: 'Topping successfully created!' }
      end
    else
      respond_to do |format|
        format.turbo_stream do
          render turbo_stream: turbo_stream.replace('toppings_form', partial: 'form', locals: { topping: @topping })
        end
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def edit
    authorize @topping
    respond_to do |format|
      format.turbo_stream do
        render turbo_stream: turbo_stream.replace('toppings_form', partial: 'form', locals: { topping: @topping })
      end
      format.html
    end
  end  

  def update
    authorize @topping
    if @topping.update(topping_params)
      respond_to do |format|
        format.turbo_stream do
          render turbo_stream: [
            turbo_stream.replace('toppings_form', partial: 'form', locals: { topping: Topping.new }),
            turbo_stream.replace("topping_#{@topping.id}", partial: 'topping', locals: { topping: @topping })
          ]
        end
        format.html { redirect_to toppings_path, notice: 'Topping was successfully updated.' }
      end
    else
      respond_to do |format|
        format.turbo_stream do
          render turbo_stream: turbo_stream.replace('toppings_form', partial: 'form', locals: { topping: @topping })
        end
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    authorize @topping
    if @topping.destroy
      respond_to do |format|
        format.html { redirect_to toppings_path, notice: 'Topping was successfully deleted.' }
        format.turbo_stream
      end
    else
      flash[:error] = "An error occurred while deleting the topping."
      redirect_to toppings_path
    end
  end

  private

  def set_topping
    @topping = Topping.find_by(id: params[:id])
  end

  def topping_params
    params.require(:topping).permit(:name, :quantity, :price_per_piece)
  end
end

app/views/toppings/_form.html.erb
<%= form_with model: topping, url: topping.persisted? ? topping_path(topping) : toppings_path, 
                method: topping.persisted? ? :patch : :post, 
                data: { turbo_frame: "toppings_form" }, 
                class: "needs-validation" do |f| %>
  <div class="card-body">
    <div class="card shadow-lg rounded m-2">
      <h3 class="mb-0 text-center card-header bg-success text-white"><%= true ? "Manage this Topping" : "Stock a new Topping" %></h3>
      <div class="m-3">
        <%= f.label :name, "Topping Name", class: "form-label text-secondary" %>
        <%= f.text_field :name, class: "form-control", placeholder: "Enter topping name", required: true %>
      </div>

      <div class="m-3">
        <%= f.label :quantity, "Stock Quantity", class: "form-label text-secondary" %>
        <%= f.number_field :quantity, class: "form-control", min: "0", placeholder: "Enter available stock", required: true %>
      </div>

      <div class="m-3">
        <%= f.label :price_per_piece, "Price per Piece ($)", class: "form-label text-secondary" %>
        <%= f.number_field :price_per_piece, class: "form-control", step: "0.01", min: "0", placeholder: "Enter price per piece", required: true %>
      </div>

      <div class="text-center">
        <%= f.submit topping.persisted? ? "Update Topping" : "Create Topping", class: "btn btn-success px-4" %>
        <%= link_to "Cancel", toppings_path, class: "btn btn-secondary m-2"%>
      </div>
    </div>
  </div>
  <% end %>

app/views/toppings/_topping.html.erb
<tr id="topping_<%= topping.id %>">
  <td><%= topping.name %></td>
  <td><%= topping.quantity %></td>
  <td><%= number_to_currency(topping.price_per_piece, unit: "$") %></td>
  <td class="text-center">
    <%= link_to "Edit", edit_topping_path(topping), data: { turbo_frame: "toppings_form" }, class: "btn btn-outline-dark" %>
    <%= link_to "Delete", topping_path(topping), 
          data: { turbo_method: :delete, turbo_confirm: "Are you sure you want to delete this topping?" }, 
          class: "btn btn-outline-dark" %>
  </td>
</tr>

app/views/toppings/destroy.turbo_stream.erb
<turbo-stream action="remove" target="topping_<%= @topping.id %>"></turbo-stream>

app/views/toppings/edit.html.erb
<%= turbo_frame_tag "toppings_form" do %>
  <%= render "form", topping: @topping %>
<% end %>

app/views/toppings/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-7">
      <div class="card shadow-lg rounded m-2">
        <div class="card-header bg-success text-white">
          <h3 class="mb-0 text-center">Toppings List</h3>
        </div>
        <div class="card-body">
          <table class="table table-bordered table-striped">
            <thead class="table-dark">
              <tr>
                <th>Name</th>
                <th>In Stock</th>
                <th>Price per Piece</th>
                <th class="text-center">Actions</th>
              </tr>
            </thead>
            <tbody id="toppings_list">
              <%= render partial: "topping", collection: @toppings, as: :topping %>
            </tbody>
          </table>
        </div>
      </div>
    </div>

    <div class="col-lg-5">
      <%= turbo_frame_tag "toppings_form", data: { turbo_cache: "false" } do %> 
        <%= render "form", topping: Topping.new %>
      <% end %>
    </div>
  </div>
</div>